/// <reference types="vite/client" />
import { convexTest } from "convex-test";
import { exportPKCS8, generateKeyPair } from "jose";
import { beforeAll, describe, expect, test, vi } from "vitest";
import { api } from "./_generated/api";
import type { Id } from "./_generated/dataModel";
import schema from "./schema";
const modules = import.meta.glob("./**/*.ts");
vi.mock("./storage/r2Client", () => ({ createPresignedPutUrl: vi.fn(async () => "https://upload.test/project"), headPublicMediaObject: vi.fn(async () => ({ ContentType: "image/jpeg", ContentLength: 12, ETag: '"etag"' })), readPublicMediaSignature: vi.fn(async () => new Uint8Array([0xff, 0xd8, 0xff])), deletePublicMediaObject: vi.fn(async () => undefined) }));
beforeAll(async () => { const { privateKey } = await generateKeyPair("RS256", { extractable: true }); process.env.JWT_PRIVATE_KEY = await exportPKCS8(privateKey); process.env.CONVEX_SITE_URL = "https://example.convex.site"; process.env.R2_ACCOUNT_ID = "0123456789abcdef0123456789abcdef"; process.env.R2_ACCESS_KEY_ID = "key"; process.env.R2_SECRET_ACCESS_KEY = "secret"; process.env.R2_BUCKET_NAME = "bucket"; process.env.R2_ENDPOINT = "https://r2.example"; process.env.R2_PUBLIC_BASE_URL = "https://media.example"; });
type T = ReturnType<typeof convexTest>;
async function user(t: T, accountType: "client" | "company" = "client", onboardingStatus: "pending" | "completed" = "completed") { return t.run((ctx) => ctx.db.insert("users", { email: `${crypto.randomUUID()}@test.dev`, accountType, onboardingStatus, countryCode: "MA", createdAt: 1, updatedAt: 1 })); }
function as(t: T, id: Id<"users">) { return t.withIdentity({ subject: `${id}|session` }); }
async function draft(t: T, id: Id<"users">) { return (await as(t, id).mutation(api.projects.index.initializeDraft, {})).projectId; }
async function complete(t: T, id: Id<"users">, projectId: Id<"projects">) { const c = as(t, id); await c.mutation(api.projects.index.saveCategory, { projectId, primaryCategory: "renovation" }); await c.mutation(api.projects.index.saveLocation, { projectId, city: "rabat" }); await c.mutation(api.projects.index.saveDetails, { projectId, title: "Rénovation appartement", propertyType: "apartment", surfaceUnknown: true, description: "Rénovation complète de l’appartement avec remise aux normes." }); await c.mutation(api.projects.index.saveBudget, { projectId, budgetRange: "unknown" }); await c.mutation(api.projects.index.saveTimeline, { projectId, timeline: "flexible" }); await c.mutation(api.projects.index.saveFiles, { projectId, imageUploadTokens: [], documents: [] }); }

describe("project wizard", () => {
  test("only an onboarded client creates and resumes one MA draft", async () => { const t = convexTest(schema, modules); const client = await user(t); const company = await user(t, "company"); const pending = await user(t, "client", "pending"); await expect(t.mutation(api.projects.index.initializeDraft, {})).rejects.toThrow("NOT_AUTHENTICATED"); await expect(as(t, company).mutation(api.projects.index.initializeDraft, {})).rejects.toThrow("CLIENT_ACCOUNT_REQUIRED"); await expect(as(t, pending).mutation(api.projects.index.initializeDraft, {})).rejects.toThrow("CLIENT_ONBOARDING_REQUIRED"); const first = await as(t, client).mutation(api.projects.index.initializeDraft, {}); const second = await as(t, client).mutation(api.projects.index.initializeDraft, {}); expect(second).toEqual({ projectId: first.projectId, resumed: true }); const rows = await t.run((ctx) => ctx.db.query("projects").withIndex("by_clientId", (q) => q.eq("clientId", client)).collect()); expect(rows).toHaveLength(1); expect(rows[0]).toMatchObject({ countryCode: "MA", status: "draft", visibility: "marketplace" }); });
  test("ownership protects edits and R2 upload permission", async () => { const t = convexTest(schema, modules); const owner = await user(t); const other = await user(t); const projectId = await draft(t, owner); await expect(as(t, other).mutation(api.projects.index.saveCategory, { projectId, primaryCategory: "renovation" })).rejects.toThrow("PROJECT_NOT_FOUND"); await expect(as(t, other).action(api.projects.media.requestImageUpload, { projectId, contentType: "image/jpeg", size: 12 })).rejects.toThrow("PROJECT_NOT_FOUND"); });
  test("validates stable category/city/surface/budget/timeline values and resumes fields", async () => { const t = convexTest(schema, modules); const id = await user(t); const c = as(t, id); const projectId = await draft(t, id); await expect(c.mutation(api.projects.index.saveCategory, { projectId, primaryCategory: "other" })).rejects.toThrow("INVALID_PROJECT_CATEGORY"); await expect(c.mutation(api.projects.index.saveCategory, { projectId, primaryCategory: "bad" as "other" })).rejects.toThrow(); await expect(c.mutation(api.projects.index.saveLocation, { projectId, city: "bad" as "rabat" })).rejects.toThrow(); await c.mutation(api.projects.index.saveCategory, { projectId, primaryCategory: "other", customCategoryText: "Tadelakt" }); await c.mutation(api.projects.index.saveLocation, { projectId, city: "agadir" }); await expect(c.mutation(api.projects.index.saveDetails, { projectId, title: "Projet valide", propertyType: "house", surface: -2, surfaceUnknown: false, description: "Description suffisamment longue pour le test du projet." })).rejects.toThrow("INVALID_PROJECT_SURFACE"); await c.mutation(api.projects.index.saveDetails, { projectId, title: "Projet valide", propertyType: "house", surfaceUnknown: true, description: "Description suffisamment longue pour le test du projet." }); await c.mutation(api.projects.index.saveBudget, { projectId, budgetRange: "unknown" }); await expect(c.mutation(api.projects.index.saveBudget, { projectId, budgetRange: "bad" as "unknown" })).rejects.toThrow(); await c.mutation(api.projects.index.saveTimeline, { projectId, timeline: "flexible" }); await expect(c.mutation(api.projects.index.saveTimeline, { projectId, timeline: "bad" as "flexible" })).rejects.toThrow(); expect((await c.query(api.projects.index.getWizard, {})).draft).toMatchObject({ primaryCategory: "other", city: "agadir", surfaceUnknown: true, budgetUnknown: true, timeline: "flexible", lastCompletedStep: 5 }); });
  test("optional files work and a verified R2 image is owner-bound and single-use", async () => { const t = convexTest(schema, modules); const id = await user(t); const c = as(t, id); const projectId = await draft(t, id); await c.mutation(api.projects.index.saveFiles, { projectId, imageUploadTokens: [], documents: [] }); const intent = await c.action(api.projects.media.requestImageUpload, { projectId, contentType: "image/jpeg", size: 12 }); await c.action(api.projects.media.verifyImageUpload, { uploadToken: intent.uploadToken }); await c.mutation(api.projects.index.saveFiles, { projectId, imageUploadTokens: [intent.uploadToken], documents: [] }); await expect(c.mutation(api.projects.index.saveFiles, { projectId, imageUploadTokens: [intent.uploadToken], documents: [] })).rejects.toThrow("INVALID_PROJECT_IMAGE"); expect(await t.run((ctx) => ctx.db.query("projectMedia").withIndex("by_projectId", (q) => q.eq("projectId", projectId)).collect())).toHaveLength(1); });
  test("private document URL is owner-only", async () => { const t = convexTest(schema, modules); const owner = await user(t); const other = await user(t); const projectId = await draft(t, owner); const storageId = await t.run((ctx) => ctx.storage.store(new Blob(["pdf"]))); const attachmentId = await t.run((ctx) => ctx.db.insert("projectAttachments", { projectId, clientId: owner, storageId, fileName: "plan.pdf", contentType: "application/pdf", size: 3, createdAt: 1 })); await expect(as(t, owner).query(api.projects.index.getAttachmentDownloadUrl, { attachmentId })).resolves.toEqual(expect.any(String)); await expect(as(t, other).query(api.projects.index.getAttachmentDownloadUrl, { attachmentId })).rejects.toThrow("PROJECT_ATTACHMENT_NOT_FOUND"); });
  test("publish validates, transitions once, records history, and remains private pending review", async () => { const t = convexTest(schema, modules); const id = await user(t); const c = as(t, id); const projectId = await draft(t, id); await expect(c.mutation(api.projects.index.publishProject, { projectId })).rejects.toThrow("PROJECT_INCOMPLETE"); await complete(t, id, projectId); await expect(c.mutation(api.projects.index.publishProject, { projectId })).resolves.toEqual({ status: "pending_review", alreadySubmitted: false }); await expect(c.mutation(api.projects.index.publishProject, { projectId })).resolves.toEqual({ status: "pending_review", alreadySubmitted: true }); expect(await t.query(api.projects.index.getPublicProject, { projectId })).toBeNull(); const history = await t.run((ctx) => ctx.db.query("projectStatusHistory").withIndex("by_projectId", (q) => q.eq("projectId", projectId)).collect()); expect(history).toHaveLength(1); expect(history[0]).toMatchObject({ oldStatus: "draft", newStatus: "pending_review", changedBy: id }); });
  test("invalid status transition is rejected and only published marketplace data is public", async () => { const t = convexTest(schema, modules); const id = await user(t); const c = as(t, id); const projectId = await draft(t, id); await complete(t, id, projectId); await t.run((ctx) => ctx.db.patch(projectId, { status: "cancelled" })); await expect(c.mutation(api.projects.index.publishProject, { projectId })).rejects.toThrow("INVALID_PROJECT_STATUS_TRANSITION"); await t.run((ctx) => ctx.db.patch(projectId, { status: "published" })); await expect(t.query(api.projects.index.getPublicProject, { projectId })).resolves.toMatchObject({ city: "rabat", primaryCategory: "renovation" }); });
});
