export const marketplaceCategories = [
  "houseConstruction",
  "renovation",
  "structural",
  "finishing",
  "architecture",
  "interior",
  "electrical",
  "plumbing",
  "joinery",
  "pool",
] as const;

export type MarketplaceCategory = (typeof marketplaceCategories)[number];

export type MarketplaceCompany = {
  id: string;
  slug: string;
  name: string;
  initials: string;
  logo?: string;
  verified: boolean;
  rating: number;
  city: string;
  projectCount: number;
  categories: readonly MarketplaceCategory[];
  services: readonly MarketplaceCategory[];
  image: string;
};

export const marketplaceCompanies: readonly MarketplaceCompany[] = [
  {
    id: "s2mbou",
    slug: "s2mbou",
    name: "S2MBOU",
    initials: "S2",
    logo: "/brand/s2mbou-logo.webp",
    verified: true,
    rating: 4.9,
    city: "Agadir",
    projectCount: 18,
    categories: ["houseConstruction", "structural"],
    services: ["houseConstruction", "structural"],
    image: "/images/portfolio-2026/projects/villa-founty-02.webp",
  },
  {
    id: "atlasHabitat",
    slug: "atlas-habitat",
    name: "Atlas Habitat",
    initials: "AH",
    verified: true,
    rating: 4.8,
    city: "Marrakech",
    projectCount: 24,
    categories: ["houseConstruction", "architecture"],
    services: ["houseConstruction", "architecture"],
    image: "/images/portfolio-2026/projects/villa-founty-construction.webp",
  },
  {
    id: "casaBati",
    slug: "casa-bati",
    name: "Casa Bâti",
    initials: "CB",
    verified: true,
    rating: 4.7,
    city: "Casablanca",
    projectCount: 31,
    categories: ["houseConstruction", "renovation"],
    services: ["houseConstruction", "renovation"],
    image: "/images/project-particulier-prive.jpg",
  },
  {
    id: "fountyVillas",
    slug: "founty-villas",
    name: "Founty Villas",
    initials: "FV",
    verified: true,
    rating: 4.9,
    city: "Agadir",
    projectCount: 12,
    categories: ["houseConstruction", "pool"],
    services: ["houseConstruction", "pool"],
    image: "/images/portfolio-2026/projects/villa-founty-01.webp",
  },
  {
    id: "darAtlas",
    slug: "dar-atlas",
    name: "Dar Atlas",
    initials: "DA",
    verified: true,
    rating: 4.8,
    city: "Rabat",
    projectCount: 16,
    categories: ["houseConstruction", "architecture"],
    services: ["architecture", "houseConstruction"],
    image: "/images/project-villa-sous-sol.jpg",
  },
  {
    id: "renovPlus",
    slug: "renov-plus",
    name: "Rénov Plus",
    initials: "RP",
    verified: true,
    rating: 4.6,
    city: "Rabat",
    projectCount: 22,
    categories: ["renovation", "finishing"],
    services: ["renovation", "finishing"],
    image: "/images/portfolio-2026/interiors/amenagement-interieur-02.webp",
  },
  {
    id: "atelierNord",
    slug: "atelier-nord",
    name: "Atelier Nord",
    initials: "AN",
    verified: true,
    rating: 4.8,
    city: "Tanger",
    projectCount: 14,
    categories: ["renovation", "interior"],
    services: ["renovation", "interior"],
    image: "/images/portfolio-2026/interiors/finitions-interieures-01.webp",
  },
  {
    id: "chantierOuvert",
    slug: "chantier-ouvert",
    name: "Chantier Ouvert",
    initials: "CO",
    verified: true,
    rating: 4.5,
    city: "Marrakech",
    projectCount: 19,
    categories: ["renovation", "structural"],
    services: ["renovation", "structural"],
    image: "/images/about-project.jpg",
  },
  {
    id: "structureAtlas",
    slug: "structure-atlas",
    name: "Structure Atlas",
    initials: "SA",
    verified: true,
    rating: 4.8,
    city: "Agadir",
    projectCount: 27,
    categories: ["structural", "houseConstruction"],
    services: ["structural", "houseConstruction"],
    image: "/images/portfolio-2026/projects/al-huda-02.webp",
  },
  {
    id: "betonLine",
    slug: "beton-line",
    name: "Béton Line",
    initials: "BL",
    verified: true,
    rating: 4.7,
    city: "Casablanca",
    projectCount: 21,
    categories: ["structural"],
    services: ["structural", "houseConstruction"],
    image: "/images/portfolio-2026/projects/al-farah-01.webp",
  },
  {
    id: "finishLab",
    slug: "finish-lab",
    name: "Finish Lab",
    initials: "FL",
    verified: true,
    rating: 4.9,
    city: "Marrakech",
    projectCount: 17,
    categories: ["finishing", "electrical"],
    services: ["finishing", "electrical"],
    image: "/images/portfolio-2026/interiors/details-finition-02.webp",
  },
  {
    id: "oeuvreSud",
    slug: "oeuvre-sud",
    name: "Œuvre Sud",
    initials: "OS",
    verified: true,
    rating: 4.6,
    city: "Agadir",
    projectCount: 15,
    categories: ["finishing", "plumbing"],
    services: ["finishing", "plumbing"],
    image: "/images/portfolio-2026/interiors/amenagement-interieur-03.webp",
  },
  {
    id: "volumeStudio",
    slug: "volume-studio",
    name: "Volume Studio",
    initials: "VS",
    verified: true,
    rating: 4.8,
    city: "Casablanca",
    projectCount: 11,
    categories: ["architecture", "interior"],
    services: ["architecture", "interior"],
    image: "/images/hero-architecture.jpg",
  },
  {
    id: "facadeAtelier",
    slug: "facade-atelier",
    name: "Façade Atelier",
    initials: "FA",
    verified: true,
    rating: 4.7,
    city: "Rabat",
    projectCount: 13,
    categories: ["architecture", "structural"],
    services: ["architecture", "structural"],
    image: "/images/portfolio-2026/exteriors/facades-travaux-exterieurs-02.webp",
  },
  {
    id: "interieurAgadir",
    slug: "interieur-agadir",
    name: "Intérieur Agadir",
    initials: "IA",
    verified: true,
    rating: 4.9,
    city: "Agadir",
    projectCount: 20,
    categories: ["interior", "joinery"],
    services: ["interior", "joinery"],
    image: "/images/portfolio-2026/interiors/amenagement-interieur-01.webp",
  },
  {
    id: "atelierMatiere",
    slug: "atelier-matiere",
    name: "Atelier Matière",
    initials: "AM",
    verified: true,
    rating: 4.8,
    city: "Marrakech",
    projectCount: 9,
    categories: ["interior"],
    services: ["interior", "finishing"],
    image: "/images/portfolio-2026/interiors/revetements-decoratifs-01.webp",
  },
  {
    id: "lumiereHabitat",
    slug: "lumiere-habitat",
    name: "Lumière Habitat",
    initials: "LH",
    verified: true,
    rating: 4.7,
    city: "Casablanca",
    projectCount: 18,
    categories: ["electrical", "finishing"],
    services: ["electrical", "finishing"],
    image: "/images/portfolio-2026/interiors/faux-plafonds-eclairage-01.webp",
  },
  {
    id: "voltSud",
    slug: "volt-sud",
    name: "Volt Sud",
    initials: "VO",
    verified: true,
    rating: 4.6,
    city: "Agadir",
    projectCount: 23,
    categories: ["electrical", "plumbing"],
    services: ["electrical", "plumbing"],
    image: "/images/expertise/electricite-plomberie.webp",
  },
  {
    id: "elecCasa",
    slug: "elec-casa",
    name: "Élec Casa",
    initials: "EC",
    verified: true,
    rating: 4.8,
    city: "Casablanca",
    projectCount: 16,
    categories: ["electrical"],
    services: ["electrical", "finishing"],
    image: "/images/portfolio-2026/interiors/faux-plafonds-eclairage-03.webp",
  },
  {
    id: "hydroBati",
    slug: "hydro-bati",
    name: "Hydro Bâti",
    initials: "HB",
    verified: true,
    rating: 4.7,
    city: "Marrakech",
    projectCount: 14,
    categories: ["plumbing", "pool"],
    services: ["plumbing", "pool"],
    image: "/images/portfolio-2026/exteriors/exterieur-piscine-01.webp",
  },
  {
    id: "plomberiePlus",
    slug: "plomberie-plus",
    name: "Plomberie Plus",
    initials: "PP",
    verified: true,
    rating: 4.5,
    city: "Rabat",
    projectCount: 28,
    categories: ["plumbing"],
    services: ["plumbing", "finishing"],
    image: "/images/expertise/etancheite.webp",
  },
  {
    id: "boisForme",
    slug: "bois-forme",
    name: "Bois & Forme",
    initials: "BF",
    verified: true,
    rating: 4.8,
    city: "Rabat",
    projectCount: 12,
    categories: ["joinery"],
    services: ["joinery", "interior"],
    image: "/images/expertise/menuiserie.webp",
  },
  {
    id: "menuiserieAtlas",
    slug: "menuiserie-atlas",
    name: "Menuiserie Atlas",
    initials: "MA",
    verified: true,
    rating: 4.6,
    city: "Agadir",
    projectCount: 19,
    categories: ["joinery", "interior"],
    services: ["joinery", "interior"],
    image: "/images/expertise/aluminium.webp",
  },
  {
    id: "atelierBois",
    slug: "atelier-bois",
    name: "Atelier Bois",
    initials: "AB",
    verified: true,
    rating: 4.7,
    city: "Tanger",
    projectCount: 10,
    categories: ["joinery"],
    services: ["joinery", "interior"],
    image: "/images/expertise/pvc.webp",
  },
  {
    id: "piscinesAtlas",
    slug: "piscines-atlas",
    name: "Piscines Atlas",
    initials: "PA",
    verified: true,
    rating: 4.9,
    city: "Agadir",
    projectCount: 15,
    categories: ["pool"],
    services: ["pool", "houseConstruction"],
    image: "/images/portfolio-2026/exteriors/exterieur-piscine-02.webp",
  },
  {
    id: "aquaVilla",
    slug: "aqua-villa",
    name: "Aqua Villa",
    initials: "AV",
    verified: true,
    rating: 4.8,
    city: "Casablanca",
    projectCount: 8,
    categories: ["pool", "houseConstruction"],
    services: ["pool", "houseConstruction"],
    image: "/images/portfolio-2026/exteriors/exterieur-piscine.webp",
  },
];

export type MarketplaceOpenProject = {
  id: string;
  category: MarketplaceCategory;
  city: string;
  postedDays: number;
  proposals: number;
  verifiedClient: boolean;
};

export const marketplaceOpenProjects: readonly MarketplaceOpenProject[] = [
  { id: "0", category: "houseConstruction", city: "Agadir", postedDays: 1, proposals: 8, verifiedClient: true },
  { id: "1", category: "renovation", city: "Casablanca", postedDays: 2, proposals: 12, verifiedClient: true },
  { id: "2", category: "structural", city: "Rabat", postedDays: 3, proposals: 5, verifiedClient: true },
  { id: "3", category: "electrical", city: "Marrakech", postedDays: 4, proposals: 6, verifiedClient: false },
  { id: "4", category: "pool", city: "Agadir", postedDays: 5, proposals: 9, verifiedClient: true },
  { id: "5", category: "interior", city: "Tanger", postedDays: 6, proposals: 4, verifiedClient: true },
];

export const featuredMarketplaceCompanyIds = [
  "s2mbou",
  "atlasHabitat",
  "casaBati",
  "renovPlus",
  "atelierNord",
  "piscinesAtlas",
] as const;

export function featuredMarketplaceCompanies() {
  return featuredMarketplaceCompanyIds
    .map((id) => marketplaceCompanies.find((company) => company.id === id))
    .filter((company): company is MarketplaceCompany => company !== undefined);
}

export function companiesForCategory(category: MarketplaceCategory) {
  return marketplaceCompanies.filter((company) => company.categories.includes(category));
}

export function companyPath(slug: string) {
  return {
    pathname: "/entreprises/[slug]" as const,
    params: { slug },
  };
}
