import { ConvexError, v } from "convex/values";
import { internal } from "../_generated/api";
import { internalMutation, internalQuery } from "../_generated/server";
import { ALLOWED_PUBLIC_IMAGE_TYPES } from "../storage/constants";
import { requireClientByUserId, requireOwnedDraft } from "./access";
import { PROJECT_IMAGE_MAX_BYTES, PROJECT_UPLOAD_TTL_MS } from "./constants";

function valid(type: string, size: number) { return ALLOWED_PUBLIC_IMAGE_TYPES.has(type) && Number.isInteger(size) && size >= 1 && size <= PROJECT_IMAGE_MAX_BYTES; }
export const getUploadAccess = internalQuery({ args: { userId: v.id("users"), projectId: v.id("projects"), contentType: v.string(), size: v.number() }, returns: v.null(), handler: async (ctx, args) => { await requireClientByUserId(ctx, args.userId); await requireOwnedDraft(ctx, args.userId, args.projectId); if (!valid(args.contentType, args.size)) throw new ConvexError("INVALID_PROJECT_IMAGE"); return null; } });
export const createUploadIntent = internalMutation({ args: { userId: v.id("users"), projectId: v.id("projects"), contentType: v.string(), size: v.number(), objectKey: v.string(), uploadToken: v.string() }, returns: v.null(), handler: async (ctx, args) => { await requireClientByUserId(ctx, args.userId); await requireOwnedDraft(ctx, args.userId, args.projectId); if (!valid(args.contentType, args.size) || !args.objectKey.startsWith(`projects/${args.projectId}/images/`)) throw new ConvexError("INVALID_PROJECT_IMAGE"); const now = Date.now(); await ctx.db.insert("projectMediaUploadIntents", { projectId: args.projectId, userId: args.userId, expectedContentType: args.contentType, expectedSize: args.size, objectKey: args.objectKey, token: args.uploadToken, expiresAt: now + PROJECT_UPLOAD_TTL_MS, createdAt: now }); await ctx.scheduler.runAfter(PROJECT_UPLOAD_TTL_MS + 60_000, internal.projects.media.cleanupExpiredUploadIntent, { uploadToken: args.uploadToken }); return null; } });
export const getUploadIntentForVerification = internalQuery({ args: { userId: v.id("users"), uploadToken: v.string() }, returns: v.object({ objectKey: v.string(), expectedContentType: v.string(), expectedSize: v.number() }), handler: async (ctx, args) => { const intent = await ctx.db.query("projectMediaUploadIntents").withIndex("by_token", (q) => q.eq("token", args.uploadToken)).unique(); if (!intent || intent.userId !== args.userId || intent.claimedAt || intent.verifiedAt || intent.expiresAt < Date.now()) throw new ConvexError("INVALID_PROJECT_IMAGE"); await requireClientByUserId(ctx, args.userId); await requireOwnedDraft(ctx, args.userId, intent.projectId); if (!intent.objectKey.startsWith(`projects/${intent.projectId}/images/`)) throw new ConvexError("INVALID_PROJECT_IMAGE"); return { objectKey: intent.objectKey, expectedContentType: intent.expectedContentType, expectedSize: intent.expectedSize }; } });
export const markUploadVerified = internalMutation({ args: { userId: v.id("users"), uploadToken: v.string(), objectKey: v.string(), contentType: v.string(), size: v.number(), etag: v.optional(v.string()) }, returns: v.null(), handler: async (ctx, args) => { const intent = await ctx.db.query("projectMediaUploadIntents").withIndex("by_token", (q) => q.eq("token", args.uploadToken)).unique(); if (!intent || intent.userId !== args.userId || intent.claimedAt || intent.verifiedAt || intent.expiresAt < Date.now() || intent.objectKey !== args.objectKey || intent.expectedContentType !== args.contentType || intent.expectedSize !== args.size) throw new ConvexError("INVALID_PROJECT_IMAGE"); await requireOwnedDraft(ctx, args.userId, intent.projectId); await ctx.db.patch(intent._id, { verifiedAt: Date.now(), etag: args.etag }); return null; } });
export const getExpiredUnclaimedIntent = internalQuery({ args: { uploadToken: v.string() }, returns: v.union(v.null(), v.object({ objectKey: v.string() })), handler: async (ctx, args) => { const intent = await ctx.db.query("projectMediaUploadIntents").withIndex("by_token", (q) => q.eq("token", args.uploadToken)).unique(); return !intent || intent.claimedAt || intent.expiresAt > Date.now() ? null : { objectKey: intent.objectKey }; } });
export const deleteExpiredUnclaimedIntent = internalMutation({ args: { uploadToken: v.string(), objectKey: v.string() }, returns: v.null(), handler: async (ctx, args) => { const intent = await ctx.db.query("projectMediaUploadIntents").withIndex("by_token", (q) => q.eq("token", args.uploadToken)).unique(); if (intent && !intent.claimedAt && intent.expiresAt <= Date.now() && intent.objectKey === args.objectKey) await ctx.db.delete(intent._id); return null; } });
