export const routes = {
  home: "/",
  about: "/a-propos",
  services: "/nos-services",
  structuralWork: "/gros-oeuvre",
  finishingWork: "/second-oeuvre",
  projects: "/nos-realisations",
  contact: "/contactez-nous",
  terms: "/terms",
  privacy: "/privacy",
  helloWorld: "/hello-world",
  constructionTrends2025: "/les-nouvelles-tendances-dans-la-construction-en-2025",
  constructionBudget: "/comment-bien-preparer-son-budget-de-construction",
  constructionMaterials: "/comment-choisir-les-bons-materiaux-pour-votre-maison",
  categoryGeneral: "/category/general",
  categoryStructuralWork: "/category/gros-oeuvre",
  howItWorks: "/comment-ca-marche",
  companies: "/entreprises",
  browseProjects: "/projets",
  postProject: "/publier-un-projet",
  signIn: "/connexion",
  signUp: "/inscription",
  signUpClient: "/inscription/client",
  signUpCompany: "/inscription/entreprise",
  clientRoot: "/espace-client",
  clientDashboard: "/espace-client/tableau-de-bord",
  clientProfile: "/espace-client/profil",
  postProjectWizard: "/espace-client/projets/nouveau",
  clientProject: "/espace-client/projets/[projectId]",
  companyDashboard: "/espace-entreprise",
  companyProjects: "/espace-entreprise/projets",
  companyProject: "/espace-entreprise/projets/[projectId]",
  companyInitialQuote: "/espace-entreprise/projets/[projectId]/devis",
  companyProfileManagement: "/espace-entreprise/profil",
  clientOnboarding: "/espace-client/onboarding",
  companyOnboarding: "/espace-entreprise/onboarding",
  companyVerification: "/espace-entreprise/verification",
  companyPortfolio: "/espace-entreprise/portfolio",
  admin: "/admin",
  adminProjects: "/admin/projects",
  adminDeals: "/admin/deals",
  adminSiteVisits: "/admin/site-visits",
  adminVerification: "/admin/verification",
  adminSettings: "/admin/settings",
  seoRoot: "/seo",
  seoDashboard: "/seo/dashboard",
  seoArticles: "/seo/articles",
  seoArticleNew: "/seo/articles/new",
  seoArticle: "/seo/articles/[articleId]",
  seoMedia: "/seo/media",
  seoPages: "/seo/pages",
  seoPillars: "/seo/pillars",
  seoClusters: "/seo/clusters",
  seoBriefs: "/seo/briefs",
  messages: "/messages",
  messagesConversation: "/messages/[conversationId]",
  notifications: "/notifications",
} as const;

export type AppRoute = Exclude<
  (typeof routes)[keyof typeof routes],
  typeof routes.clientProject | typeof routes.companyProject | typeof routes.companyInitialQuote | typeof routes.messagesConversation | typeof routes.seoArticle
>;
export type DynamicAppRoute =
  | typeof routes.clientProject
  | typeof routes.companyProject
  | typeof routes.companyInitialQuote
  | typeof routes.messagesConversation
  | typeof routes.seoArticle;
export type ProtectedRoute = AppRoute;
