export const APP_ERROR_CODES = [
  "INVALID_ACCOUNT_TYPE",
  "ACCOUNT_TYPE_MISMATCH",
  "INVALID_EMAIL",
  "INVALID_CREDENTIALS",
  "ACCOUNT_EXISTS",
  "PASSWORD_TOO_SHORT",
  "TERMS_REQUIRED",
  "INVALID_PROFILE",
  "OAUTH_ACCOUNT_LINKING_BLOCKED",
  "NOT_AUTHENTICATED",
  "USER_NOT_FOUND",
  "INVALID_NAME",
  "INVALID_PHONE",
  "INVALID_CITY",
  "CLIENT_ACCOUNT_REQUIRED",
  "CLIENT_ONBOARDING_REQUIRED",
  "COMPANY_ACCOUNT_REQUIRED",
  "COMPANY_OWNER_REQUIRED",
  "COMPANY_NOT_FOUND",
  "DUPLICATE_ACCOUNT_FOUNDATION",
  "INVALID_COMPANY_MEMBERSHIP",
  "INVALID_COMPANY_NAME",
  "INVALID_LEGAL_NAME",
  "INVALID_DESCRIPTION",
  "INVALID_WEBSITE",
  "INVALID_YEARS_EXPERIENCE",
  "INVALID_FOUNDED_YEAR",
  "INVALID_SERVICE_AREAS",
  "INVALID_LANGUAGES",
  "INVALID_SERVICES",
  "DUPLICATE_COMPANY_SERVICE",
  "INVALID_LOGO",
  "INVALID_PUBLIC_MEDIA_UPLOAD",
  "PUBLIC_MEDIA_UPLOAD_FAILED",
  "PUBLIC_MEDIA_URL_NOT_CONFIGURED",
  "INVALID_VERIFICATION_STATUS",
  "COMPANY_ONBOARDING_REQUIRED",
  "INVALID_ICE",
  "INVALID_RC_NUMBER",
  "INVALID_LEGAL_REPRESENTATIVE",
  "INVALID_ADDRESS",
  "INVALID_VERIFICATION_DOCUMENT",
  "DOCUMENT_UPLOAD_FAILED",
  "COMPANY_SLUG_UNAVAILABLE",
  "INVALID_PORTFOLIO_IMAGE",
  "INVALID_PORTFOLIO_TITLE",
  "INVALID_PORTFOLIO_DESCRIPTION",
  "INVALID_PORTFOLIO_CITY",
  "INVALID_PORTFOLIO_SURFACE",
  "INVALID_PORTFOLIO_DURATION",
  "INVALID_PORTFOLIO_YEAR",
  "INVALID_PORTFOLIO_CAPTION",
  "PORTFOLIO_PROJECT_NOT_FOUND",
  "PROJECT_NOT_FOUND", "PROJECT_NOT_EDITABLE", "INVALID_PROJECT_CATEGORY", "INVALID_PROJECT_NEIGHBORHOOD",
  "INVALID_PROJECT_TITLE", "INVALID_PROJECT_SURFACE", "INVALID_PROJECT_DESCRIPTION", "INVALID_PROJECT_IMAGE",
  "PROJECT_IMAGE_UPLOAD_FAILED", "INVALID_PROJECT_DOCUMENT", "PROJECT_DOCUMENT_UPLOAD_FAILED", "PROJECT_INCOMPLETE",
  "INVALID_PROJECT_STATUS_TRANSITION", "PROJECT_ATTACHMENT_NOT_FOUND",
  "NETWORK",
  "UNKNOWN",
] as const;

export type AppErrorCode = (typeof APP_ERROR_CODES)[number];

const knownCodes = new Set<string>(APP_ERROR_CODES);

export function isAppErrorCode(value: string): value is AppErrorCode {
  return knownCodes.has(value);
}

export const ERROR_FIELD_BY_CODE: Partial<Record<AppErrorCode, string>> = {
  INVALID_EMAIL: "email",
  INVALID_CREDENTIALS: "password",
  PASSWORD_TOO_SHORT: "password",
  TERMS_REQUIRED: "acceptedTerms",
  INVALID_PROFILE: "firstName",
  INVALID_NAME: "firstName",
  INVALID_PHONE: "phone",
  INVALID_CITY: "city",
  INVALID_PROJECT_CATEGORY: "primaryCategory",
  INVALID_PROJECT_NEIGHBORHOOD: "neighborhood",
  INVALID_PROJECT_TITLE: "title",
  INVALID_PROJECT_SURFACE: "surface",
  INVALID_PROJECT_DESCRIPTION: "description",
  INVALID_PROJECT_IMAGE: "images",
  INVALID_PROJECT_DOCUMENT: "documents",
  INVALID_COMPANY_NAME: "name",
  INVALID_LEGAL_NAME: "legalName",
  INVALID_DESCRIPTION: "description",
  INVALID_WEBSITE: "website",
  INVALID_YEARS_EXPERIENCE: "yearsExperience",
  INVALID_FOUNDED_YEAR: "foundedYear",
  INVALID_SERVICE_AREAS: "serviceAreas",
  INVALID_LANGUAGES: "languages",
  INVALID_SERVICES: "services",
  INVALID_LOGO: "logo",
  INVALID_ICE: "ice",
  INVALID_RC_NUMBER: "rcNumber",
  INVALID_LEGAL_REPRESENTATIVE: "legalRepresentative",
  INVALID_ADDRESS: "address",
  INVALID_VERIFICATION_DOCUMENT: "documents",
  INVALID_PORTFOLIO_IMAGE: "coverImage",
  INVALID_PORTFOLIO_TITLE: "title",
  INVALID_PORTFOLIO_DESCRIPTION: "description",
  INVALID_PORTFOLIO_CITY: "city",
  INVALID_PORTFOLIO_SURFACE: "surface",
  INVALID_PORTFOLIO_DURATION: "durationMonths",
  INVALID_PORTFOLIO_YEAR: "year",
  INVALID_PORTFOLIO_CAPTION: "extraImages",
};

const codesByLength = [...APP_ERROR_CODES]
  .filter((code) => code !== "UNKNOWN" && code !== "NETWORK")
  .sort((a, b) => b.length - a.length);

export function findKnownCodeInText(text: string): AppErrorCode | null {
  for (const code of codesByLength) {
    if (text.includes(code)) return code;
  }
  return null;
}
